4.1 finished
Furetur/KotlinProgramming pull request #11
Opened 2020-04-11 09:56 UTC by Furetur

2020-06-06 10:11 UTC, elena-lyulina requested changes

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/file.txt
> +k: v0
Обычно все дополнительные файлы (не с кодом), картинки и тд не хранят вместе с исходным кодом. Хорошим способом их организации является создание папки resources в src/main (рядом с папкой kotlin), по идее тебе сама среда при создании новой папки предложит создать папку resources и заодно пометит ее как папку с ресусрами. В этой папке и надо хранить все файлы, причем в соответствии с тем, где ты их используешь. Если ты file.txt используешь в src/main/kotlin/homeworks/hw4/, то хранить его надо в src/main/resources/spbuhomework/hw4/file.txt, соблюдая ту же систему подпапок.
И для тестовых ресурсов аналогично.

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/supportedHashFunctions.kt
> +const val TRIVIAL_HASH_SHIFT_SIZE = 8
Выглядит конечно не очень по ООП. 
Давай все же сделаем инктрфейс для хэш-функций с каким-нибудь методом, в котором и будет реализовавывать функция. Тогда все эти константы будут полями в соответствующем классе. А еще полем заодно можно сделать имя хэш-функции.

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/supportedHashFunctions.kt
> +val supportedHashFunctionsNames = listOf("pearsonHash", "polynomialHash", "trivialHash")
списки имен тогда можно получать, проебгаясь по списку функций и беря у них поле name, так тебе не надо будет поддерживать сразу два списка (есть шансы, что при добавлении новой функции ты забудешь например добавить ее имя)

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/interactiveModeFunctions.kt
> +package homeworks.hw4
файлы в kotlin принято с большой буквы называть https://kotlinlang.org/docs/reference/coding-conventions.html#source-file-names, поправь везде, пожалуйста

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/interactiveModeFunctions.kt
> +fun get(hashTable: HashTable<String, String>, commandTokens: List<String>): String {
Тут тоже хочется ООП. Заведи интерфейс для команды, храни в каждом классе поле с количеством токенов, поле с именем команды (get, exit и тд), правильный синтаксис, cаму функцию обработки команды, будет удобнее. А то так у тебя почему-то 3 вынесена в глобальные константы, 2 -- нет, все вперемешку. Можно сделать совсем хорошо и завести не интерфейс, а абстрактный класс с реализованной проверкой синтаксиса (с абстрактными синтаксисом и кол-вом токенов) --- ты все равно ее в каждом методе вызываешь, так будешь просто эту проверку вызывать.
Ну и еще стоит  проверять, что у тебя нулевой токен совпадает с нужным словом (именем команды). Я конечно понимаю, что ты их вызываешь в соответствии с нулевым токеном уже, но а если кто-нибудь другой захочет из другого места вызвать?

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/interactiveModeFunctions.kt
> +    val file = File("./src/main/kotlin/homeworks/hw4/$filename")
Ты лучше сразу в первом сообщении пользователя предупреждай, что надо писать только имя файла, который будет искатся именно в этой папке. И тогда для этого адреса лучше завести переменную, и ее использовать в первом сообщении и тут. Или предоставь пользователю возможность указывать любой путь целиком, тогда не надо будет ничего создавать дополнительно, просто проверять, существует ли указанный пользователем файл

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/interactiveModeFunctions.kt
> +    return supportedHashFunctionsNames[hashFunctionNumber - 1]
Ну и тут если у тебя будут классы хэшфункций, то можно просто возвращать поле name выбранной функции. Так что подумай еще, нужно ли тебе хранить отдельно список имен всех функций

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/parseFile.kt
> +    val value = parsedLine[1]
У тебя так и задумано, что пробел между key и value в файле присоединяется к value? Наверное, стоит либо в файле file.txt писать по-другому, либо тут что-то исправить, а то так не очень

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/HashTable.kt
> +            throw IllegalArgumentException("Table size cannot be < 1")
у тебя сообщение не соответствует условию в ифе, определись уж, какого размера не может быть таблица :)

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/HashTable.kt
> +            // rehash
убирай ненужные комментарии перед пулл реквестом

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/HashTable.kt
> +        get() = table.filter { cell -> cell.size > 0 }.flatten().toMutableSet()
У тебя при каждом обращении к entries будет заново считаться его значение, то есть фильтроваться вся таблица и все такое. Не легче ли просто хранить список всех entries, добавляя туда entry при put и удаляя -- при remove? И тогда itemsCount не надо будет обновлять -- можно получать его как размер entries.
И ты уверен, что MutableSet тут необходим? у тебя разе могут быть два одинаковых вхождения с одним и тем же ключом?

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/HashTable.kt
> +        get() = table.map { cell -> cell.size }.max()!!
!! лучше не использовать, в случае null лучше возвращать 0, например. У пустой таблицы же 0 конфликтов

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/HashTable.kt
> +        get() = occupiedCellsCount.toFloat() / tableSize
load factor обычно считают не по количеству занятых клеток, а по общему количеству лежащих в ней элементов

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/HashTable.kt
> +    }
Одна из ключевых особенностей хэш-таблицы -- ее увеличение в случае слишком большого load factor. Это делается для того, чтобы элементов с одним и тем же хэшем было всегда не оч много, чтобы по ним можно было быстро найти элемент с нужным ключом. При увеличении таблицы элементы перерспределяются, так что элементов с одним и тем же хэшем становится меньше. Можно [документацию](https://docs.oracle.com/javase/7/docs/api/java/util/HashMap.html) реализации в джаве почитать, например:

> An instance of HashMap has two parameters that affect its performance: initial capacity and load factor. The capacity is the number of buckets in the hash table, and the initial capacity is simply the capacity at the time the hash table is created. The load factor is a measure of how full the hash table is allowed to get before its capacity is automatically increased. When the number of entries in the hash table exceeds the product of the load factor and the current capacity, the hash table is rehashed (that is, internal data structures are rebuilt) so that the hash table has approximately twice the number of buckets.
> 
> As a general rule, the default load factor (.75) offers a good tradeoff between time and space costs. Higher values decrease the space overhead but increase the lookup cost (reflected in most of the operations of the HashMap class, including get and put). The expected number of entries in the map and its load factor should be taken into account when setting its initial capacity, so as to minimize the number of rehash operations. If the initial capacity is greater than the maximum number of entries divided by the load factor, no rehash operations will ever occur.

так что при добавлении нового элемента стоит следить за тем, не слишком ли вырос load factor и в случае чего --- увеличивать размер и перераспределять всю таблицу

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/interactiveModeFunctions.kt
> +            "Max conflicts in one cell: ${hashTable.maxConflictsForKey}"
По условию еще общее число конфликтов надо выводить

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/interactiveModeFunctions.kt
> +}
В командах из одного слова тоже надо проерять количество всех токенов. Вдруг их больше, чем надо?

2020-06-06 10:11 UTC, elena-lyulina commented on src/test/kotlin/homeworks/hw4/HashTableTest.kt
> +        assertNotEquals(oldLoadFactor, hashTable.loadFactor)
Учитывая, что load factor -- это количество всех элементов / количество клеток в таблице, то он наоборот не должен меняться при изменении хэш-функции

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/interactiveModeFunctions.kt
> +        "exit" -> "exit"
Для exit лучше тоже завести класс, тогда можно будет проверить правильные синтаксис (должно быть только одно слово exit).  А в качестве реализации команды можно просто имя возвращать

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/task1.kt
> +    while (lastOutput != "exit") {
Тут лучше проверять, что lastOutput != ExitCommand.name, когда реализуешь классы для команды

2020-06-06 10:11 UTC, elena-lyulina commented on src/main/kotlin/homeworks/hw4/interactiveModeFunctions.kt
> +    putPairsIntoHashTable(hashTable, pairs)
зачем тебе отдельная функция для добавления пар в таблицу? еще и реализованная зачем-то в task1.kt, что по смыслу прям оч странно. У тебя же есть putAll в хэш-таблице, [переведи](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/to-map.html#tomap) просто список пар в Map и используй ее.

2020-06-06 17:56 UTC, Furetur commented on src/main/kotlin/homeworks/hw4/supportedHashFunctions.kt
> +const val TRIVIAL_HASH_SHIFT_SIZE = 8
Может это не по ООП, но я бы такое реализовал как-то похоже на
`typealias HashFunction<T> = (T) -> Int`
А все хэшфункции, которые принимают параметры (как `pearsonHash` допустим принимает `PEARSON_RESOLUTION`) были бы типа
`(params) -> HashFunction`.
Допустим `pearsonHash: (Int) -> HashFunction`.
Почему создавать интерфейс для хэшфункции лучше такой реализации?

2020-06-07 12:21 UTC, Furetur commented on src/main/kotlin/homeworks/hw4/HashTable.kt
> +        get() = table.filter { cell -> cell.size > 0 }.flatten().toMutableSet()
Если я не ошибаюсь, интерфейс `MutableMap` требует, чтобы поле `entries` было типа `MutableSet`

2020-06-07 15:40 UTC, Furetur commented on src/main/kotlin/homeworks/hw4/parseFile.kt
> +    val value = parsedLine[1]
У меня сделано так, что все, что перед `:` относится к ключу, а все, что после - к значению, для того чтобы можно было делать любые ключи и значения. Я, конечно, могу делать `trim`, но я решил так не делать, и у меня даже есть тесты, которые проверяют что ключи и значения не триммятся. А с тем, что в `file.txt` было написано странно, я согласен. Я убрал путающие пробелы)

2020-06-08 12:59 UTC, SpirinEgor approved these changes

2020-06-18 16:54 UTC, merged