Hw5 task1
Furetur/KotlinProgramming pull request #13
Opened 2020-05-01 12:09 UTC by Furetur

2020-06-06 13:16 UTC, SpirinEgor requested changes

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/CustomSerializable.kt
> +interface CustomSerializable {
https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +    private var root = Node()
`val`, как у бора может корень измениться?

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +    private var rootSize: Int = 0
А за что эта переменная отвечает? Может она должна быть внутри класса `Node`

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +    class Node(private var isTerminal: Boolean = false) : Iterable<String> {
Наверное, надо `private`

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +            return children[symbol]
А если будет `null` и не создавалась? Тут упадёт или вернётся `null`?

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +        private fun traverse(value: String, build: Boolean = false): Pair<List<Node>, Boolean> {
Вместо пары лучше датаклассы задавать, они более понятные (сейчас вообще непонятно, что за булеан там возвращается)

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +        private fun traverse(value: String, build: Boolean = false): Pair<List<Node>, Boolean> {
Вместо `build` лучше назвать, как и в функции выше.

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +            val (path) = traverse(value, true)
скобочки лишние, либо надо полностью разыменовывать. Если есть ненужный аргумент, то надо `_` указывать

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +            return when (other) {
`when` для проверки для одного условия как-то странно, можно просто `if`

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +            result = 31 * result + children.hashCode()
Что за магическая константа?

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +            rootSize += 1
Ааа, это количество слов в дереве, ну надо более понятно назвать

2020-06-06 13:16 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +        root = Node()
Я бы сказал, что для удаления надо пройтись по дереву и почистить мапы

2020-06-07 17:07 UTC, Furetur commented on src/main/kotlin/homeworks/hw5/Trie.kt
> +            return children[symbol]
Вернется `null`. Что значит, что ребенок для данного `symbol` не найден. `get` у `HashMap` же возвращает `null`, если значение не найдено.
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-hash-map/get.html

2020-06-08 08:31 UTC, SpirinEgor approved these changes

2020-06-18 16:53 UTC, merged