6.1 finished
Furetur/KotlinProgramming pull request #14
Opened 2020-05-05 12:52 UTC by Furetur

2020-06-07 12:34 UTC, SpirinEgor requested changes
Надо показать результаты замеров

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/asyncQuickSort.kt
> +    coroutineScope {
Зачем тут Scope? Раз функция suspend, то она уже запущена в нужном скоупе

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/asyncQuickSort.kt
> +            return@coroutineScope
А почему возвращение туда, а не в целом из функции?

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/asyncQuickSort.kt
> +        }
Лучше последовательно сделать 2 запуска, а в начале сортировки проверять, что края валидны. Количество условий сразу сократится

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/measurers.kt
> +fun <E : Comparable<E>> measureAsyncQuicksort(list: MutableList<E>): Long {
Почему тут `E`, а выше `T`. Это не замечание, скорее интересно)

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/measurers.kt
> +fun <E : Comparable<E>> measureTime(list: MutableList<E>): Pair<Long, Long> {
Вместо пар лучше датаклассы заводить

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/measurers.kt
> +    val list2 = list.toMutableList()
Лучше `.clone()` использовать, чтобы было понятно, а что тут происходит

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/measurers.kt
> +    )
`ch in 'a'..'z'`

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/measurers.kt
> +fun getRandomString(): String {
Не строка тогда уж, а случайная перестановка букв

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/partition.kt
> +    list[list.lastIndex] = temp
`swap` через `also` в одну строчку делает

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/quickSort.kt
> +    }
Здесь тоже можно уменьшить число if

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/task1.kt
> +    println("${getColumn("test")}|${getColumn("quicksort (ms)")}|${getColumn("async quicksort (ms)")}")
Это всё надо оформить в какую-нибудь табличку и прикрепить к пр

2020-06-07 12:34 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw6/task1.kt
> +const val BIG_TEST_SIZE = 10000
Может лучше сделать класс `Benchmarks`, а это будут его поля?
Лучше чем глобально писать

2020-06-08 06:26 UTC, Furetur commented on src/main/kotlin/homeworks/hw6/task1.kt
> +const val BIG_TEST_SIZE = 10000
Я оставил эти константы в мейне, потому что они относятся к задаче, то есть к `Task1.kt`. Но сделал бенчмарки и таблицу отдельными классами, которые принимают эти константы, чтобы эти классы можно было переиспользовать

2020-06-08 06:27 UTC, Furetur commented on src/main/kotlin/homeworks/hw6/asyncQuickSort.kt
> +            return@coroutineScope
Иначе почему-то не получается. Можно только `return@coroutineScope`

2020-06-08 06:27 UTC, Furetur commented on src/main/kotlin/homeworks/hw6/measurers.kt
> +fun <E : Comparable<E>> measureAsyncQuicksort(list: MutableList<E>): Long {
Опечатка). Я стараюсь писать `E`, потому что элемент

2020-06-08 06:31 UTC, Furetur commented on src/main/kotlin/homeworks/hw6/measurers.kt
> +    val list2 = list.toMutableList()
Я не видел нигде метода `.clone()`, я знаю, что он в джаве везде есть, но в котлине я его не находил. У массивов (не у списков) есть метод `.copyOf()`, который решает такую проблему, а для списков все советуют делать также, как и я (ну я из интернета решение взял)
https://stackoverflow.com/questions/46846025/how-to-clone-or-copy-a-list-in-kotlin/52907983
https://stackoverflow.com/questions/49053432/how-to-clone-object-in-kotlin

2020-06-08 07:37 UTC, SpirinEgor approved these changes

2020-06-18 16:53 UTC, merged